Revert "ci: use zig as the C compiler for all composer platforms (#442)" (#463)
This reverts commit 20c7f1155f2d09cb60e57c7ad3c78af1babb98a4.

The "plugin" packages produced for max osx are broken. Until we figure
out how Go plugins can properly be cross-compiled to OSX, let's better
revert the zig change and keep only packages for Linux.

Details below:

```
$ ./cli/out/boe-darwin-arm64 download example-go --dev --path /tmp/down
→ Downloading example-go for darwin/arm64...
Extension downloaded to: /tmp/down/extensions/goplugin/example-go/0.7.0-dev
```
Use this simple main to load the cross-compiled Go plugin:
```
package main

import (
	"os"
	"plugin"
)

func main() {
	_, err := plugin.Open(os.Args[1])
	if err != nil {
		panic(err)
	}
}
```
Then try to load it:
```
$ go run main.go /tmp/down/extensions/goplugin/example-go/0.7.0-dev/plugin.so
fatal error: runtime: no plugin module data

goroutine 1 gp=0x5a7d3a73a1e0 m=0 mp=0x1008d5d60 [running]:
runtime.throw({0x1007ab971?, 0x5a7d3a73a1e0?})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/panic.go:1229 +0x38 fp=0x5a7d3a7c1bb0 sp=0x5a7d3a7c1b80 pc=0x100763648
plugin.lastmoduleinit()
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/plugin.go:23 +0x700 fp=0x5a7d3a7c1ca0 sp=0x5a7d3a7c1bb0 pc=0x100763d60
plugin.open({0x16f716e57, 0x3c})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/plugin/plugin_dlopen.go:77 +0x3f8 fp=0x5a7d3a7c1f10 sp=0x5a7d3a7c1ca0 pc=0x1007a52a8
plugin.Open(...)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/plugin/plugin.go:84
main.main()
	/Users/nacx/src/built-on-envoy/main.go:9 +0x34 fp=0x5a7d3a7c1f30 sp=0x5a7d3a7c1f10 pc=0x1007a5904
runtime.main()
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:290 +0x2b4 fp=0x5a7d3a7c1fd0 sp=0x5a7d3a7c1f30 pc=0x1007327a4
runtime.goexit({})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/asm_arm64.s:1447 +0x4 fp=0x5a7d3a7c1fd0 sp=0x5a7d3a7c1fd0 pc=0x100769e64

goroutine 2 gp=0x5a7d3a73ad20 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:462 +0xbc fp=0x5a7d3a7aef90 sp=0x5a7d3a7aef70 pc=0x100763e2c
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:468
runtime.forcegchelper()
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:375 +0xb4 fp=0x5a7d3a7aefd0 sp=0x5a7d3a7aef90 pc=0x100732ac4
runtime.goexit({})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/asm_arm64.s:1447 +0x4 fp=0x5a7d3a7aefd0 sp=0x5a7d3a7aefd0 pc=0x100769e64
created by runtime.init.7 in goroutine 1
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:363 +0x24

goroutine 3 gp=0x5a7d3a73b680 m=nil [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:462 +0xbc fp=0x5a7d3a7af770 sp=0x5a7d3a7af750 pc=0x100763e2c
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:468
runtime.bgsweep(0x5a7d3a75e100)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mgcsweep.go:279 +0x9c fp=0x5a7d3a7af7b0 sp=0x5a7d3a7af770 pc=0x10071ca4c
runtime.gcenable.gowrap1()
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mgc.go:214 +0x20 fp=0x5a7d3a7af7d0 sp=0x5a7d3a7af7b0 pc=0x10070dae0
runtime.goexit({})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/asm_arm64.s:1447 +0x4 fp=0x5a7d3a7af7d0 sp=0x5a7d3a7af7d0 pc=0x100769e64
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mgc.go:214 +0x6c

goroutine 4 gp=0x5a7d3a73b860 m=nil [GC scavenge wait]:
runtime.gopark(0x5a7d3a75e100?, 0x1007b0470?, 0x1?, 0x0?, 0x5a7d3a73b860?)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:462 +0xbc fp=0x5a7d3a7aff60 sp=0x5a7d3a7aff40 pc=0x100763e2c
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:468
runtime.(*scavengerState).park(0x1008d5260)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mgcscavenge.go:425 +0x5c fp=0x5a7d3a7aff90 sp=0x5a7d3a7aff60 pc=0x10071a50c
runtime.bgscavenge(0x5a7d3a75e100)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mgcscavenge.go:653 +0x44 fp=0x5a7d3a7affb0 sp=0x5a7d3a7aff90 pc=0x10071aa64
runtime.gcenable.gowrap2()
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mgc.go:215 +0x20 fp=0x5a7d3a7affd0 sp=0x5a7d3a7affb0 pc=0x10070daa0
runtime.goexit({})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/asm_arm64.s:1447 +0x4 fp=0x5a7d3a7affd0 sp=0x5a7d3a7affd0 pc=0x100769e64
created by runtime.gcenable in goroutine 1
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mgc.go:215 +0xac

goroutine 5 gp=0x5a7d3a73ba40 m=nil [GOMAXPROCS updater (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:462 +0xbc fp=0x5a7d3a7b0770 sp=0x5a7d3a7b0750 pc=0x100763e2c
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:468
runtime.updateMaxProcsGoroutine()
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:7095 +0xf4 fp=0x5a7d3a7b07d0 sp=0x5a7d3a7b0770 pc=0x100741234
runtime.goexit({})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/asm_arm64.s:1447 +0x4 fp=0x5a7d3a7b07d0 sp=0x5a7d3a7b07d0 pc=0x100769e64
created by runtime.defaultGOMAXPROCSUpdateEnable in goroutine 1
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:7083 +0x48

goroutine 6 gp=0x5a7d3a7ee1e0 m=nil [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0xb8?, 0xe5?, 0x100764974?)
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/proc.go:462 +0xbc fp=0x5a7d3a7ae580 sp=0x5a7d3a7ae560 pc=0x100763e2c
runtime.runFinalizers()
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mfinal.go:210 +0x100 fp=0x5a7d3a7ae7d0 sp=0x5a7d3a7ae580 pc=0x10070cbb0
runtime.goexit({})
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/asm_arm64.s:1447 +0x4 fp=0x5a7d3a7ae7d0 sp=0x5a7d3a7ae7d0 pc=0x100769e64
created by runtime.createfing in goroutine 1
	/opt/homebrew/Cellar/go/1.26.4/libexec/src/runtime/mfinal.go:172 +0x78
exit status 2
```

Signed-off-by: Ignasi Barrera <ignasi@tetrate.io>